version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: aff-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - proxy-network
      
networks:
  proxy-network:
    driver: bridge