name: Deploy Nginx Reverse Proxy

on:
  push:
    branches:
      - master  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up SSH key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      # Step 3: Add Known Hosts
      - name: Add Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_DOMAIN }} >> ~/.ssh/known_hosts

      # Step 4: Deploy with Docker Compose
      - name: Deploy with Docker Compose
        run: |
          # Transfer files to server
          rsync -avz --progress --delete -e "ssh" ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_DOMAIN }}:~/aff_infra/

          # SSH to deploy with minimal downtime
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_DOMAIN }} << 'EOF'
            mkdir -p ~/aff_infra
            cd ~/aff_infra

            # Store deployment version
            echo "${{ github.sha }}" > deploy_version.txt

            # Pull and build images
            docker-compose pull
            docker-compose build

            # Stop and rename existing Nginx container to avoid port conflict
            if docker ps -q -f name=aff_infra_nginx_1; then
              docker stop aff_infra_nginx_1
              docker rename aff_infra_nginx_1 aff_infra_nginx_old || true
            fi

            # Start new containers
            docker-compose up -d --build

            # Wait for Nginx to be ready
            echo "Waiting for Nginx to be ready..."
            timeout 60s bash -c "until docker inspect aff_infra_nginx_1 --format '{{.State.Health.Status}}' | grep -q 'healthy'; do sleep 5; echo 'Checking...'; done" || {
              echo "Nginx health check failed or timed out, attempting curl test..."
              # Fallback: Test Nginx directly with curl
              timeout 30s bash -c "until curl -s -f http://localhost:80; do sleep 5; echo 'Checking...'; done" || {
                echo "Health check and curl test failed, rolling back..."
                docker-compose down
                if docker ps -a -q -f name=aff_infra_nginx_old; then
                  docker rename aff_infra_nginx_old aff_infra_nginx_1 || true
                  docker start aff_infra_nginx_1
                fi
                exit 1
              }
            }

            # Clean up old containers and images
            docker container rm -f aff_infra_nginx_old || true
            docker image prune -f
            docker container prune -f

            # Verify deployment
            docker-compose ps
          EOF