name: Deploy Nginx Reverse Proxy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Transfer files and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_DOMAIN }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create directory if it doesn't exist
            mkdir -p ~/aff_infra
            cd ~/aff_infra

            # Store deployment version
            echo "${{ github.sha }}" > deploy_version.txt
          # Run rsync separately to transfer files from runner to server
      - name: Sync files to server
        run: |
          rsync -avz --progress --delete -e "ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no" ${{ github.workspace }}/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_DOMAIN }}:~/aff_infra/

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_DOMAIN }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/aff_infra
            
            # Pull and deploy
            docker compose pull
            docker compose up -d --build --force-recreate --remove-orphans
            
            # Wait for Nginx to be ready
            timeout 30s bash -c "until curl -s -f http://localhost:80/health; do sleep 2; echo 'Checking...'; done" || {
              echo "Deployment failed, rolling back..."
              docker compose down
              exit 1
            }
            
            # Cleanup
            docker image prune -f
            docker container prune -f