name: Deploy Nginx Reverse Proxy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_DOMAIN }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create directory and sync files
            mkdir -p ~/aff_infra
            cd ~/aff_infra
            
            # Store deployment version
            echo "${{ github.sha }}" > deploy_version.txt

            # Export variables for rsync
            export RSYNC_RSH="ssh -o StrictHostKeyChecking=no"
            
            # Pull and deploy
            docker compose pull
            docker compose up -d --build --force-recreate --remove-orphans
            
            # Wait for Nginx to be ready (simplified health check)
            timeout 30s bash -c "until curl -s -f http://localhost:80; do sleep 2; echo 'Checking...'; done" || {
              echo "Deployment failed, rolling back..."
              docker compose down
              exit 1
            }
            
            # Cleanup
            docker image prune -f
            docker container prune -f